/*
 * Bundles src/ plus its two npm dependencies into a single CommonJS main.js,
 * which is what Obsidian loads.
 *
 * `obsidian` is external — the app provides it at runtime. Nothing else is:
 * the plugin has to run on a phone, where there is no node_modules to resolve
 * against.
 */

import esbuild from 'esbuild';

const watch = process.argv.includes('--watch');

const banner = `/*
 * Supernote Annotations for Obsidian — GENERATED by esbuild, do not edit.
 * Sources: https://github.com/JUNSKIx1/obsidian-supernote-annotations
 *
 * Bundles pdf-lib (MIT) and supernote-typescript (GPL-3.0-or-later).
 * This bundle is therefore GPL-3.0-or-later as a whole.
 */
`;

const options = {
  entryPoints: ['src/main.js'],
  bundle: true,
  outfile: 'main.js',
  format: 'cjs',
  platform: 'browser',
  target: 'es2018',
  external: ['obsidian', 'electron'],
  logLevel: 'info',
  sourcemap: false,
  treeShaking: true,
  // Minified because pdf-lib is a megabyte of library and this file ships in
  // every release. Not obfuscation: `npm run build` reproduces it byte for byte
  // from the sources in this repo, which is what the directory's build
  // verification checks.
  minify: !watch,
  banner: { js: banner },
};

if (watch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
} else {
  await esbuild.build(options);
}
